on:
  push:
    branches:
      - "*"
    tags:
      - "*"
env:
  SSH_KEY: "Test"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -o backend ./cmd
